### ISSUE TITLE
Install staking wallet on Ubuntu

### ISSUE THREAD

**Issue by decadeofdata** [stratisproject/stratisX#17]
Yo,

Downloaded the sourcecode.zip.
Extracted the folder. 

Followed the instructions.

"::

    apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools \
        build-essential libboost-dev libboost-system-dev \
        libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev \
        libssl-dev libdb++-dev libminiupnpc-dev

then execute the following:

::

    qmake
    make"

It doesnt say anything about it being installed and i dont see it in my applications list.

**Comment by DemonRx** [comment]
The binary file you are searching for is in the stratisX folder as **stratis-qt** it does not get installed to the system or application menus

**Comment by decadeofdata** [comment]
Thanks.

Does the wallet have to open all the time to stake? Or can we close the application?

**Comment by dev0tion** [comment]
Yes @ResponsiveWebApps, it has to be open and unlocked for staking.

**Comment by diogogomes** [comment]
Do you have plans to release deb, snap or appimage package?
