### ISSUE TITLE
Reset wallet?

### ISSUE THREAD

**Issue by LanFeusT23** [stratisproject/stratisX#19]
As I was messing around with the wallet before doing any transaction I managed to set a passphrase that I somehow misstyped and can't recover...

Thankfully I have nothing on the wallet but I'm unable to reset anything, deleting the .exe file and re-downloading and launch it it always goes back to my previous wallet.

How do I go about resetting this wallet so I can start over?

Thanks,

**Comment by LanFeusT23** [comment]
Nevermind! Deleted the wallet.dat file in the %APPDATA% that did the trick!

**Comment by dev0tion** [comment]
Our job sure becomes easier when people start solving their own issues @LanFeusT23 :+1: 
Glad it all worked out.
