### ISSUE TITLE
wallet running on Max Sierra, "0 connections to stratis network" 

### ISSUE THREAD

**Issue by steelliberty** [stratisproject/stratisX#20]
when I hover over center icon I get "not staking because wallet is offline" --

Is this just a start up issue?  It has been up and active for an hour.

**Comment by steelliberty** [comment]
How can import the master keys from the Stratis Staking wallet, which does not function to the Electrum Wallet which will work?  I have stratis coins in limbo waiting for a home.  They were sent to address created in the Staking wallet ..

**Comment by dev0tion** [comment]
You can add a few nodes to stratis.conf.
Get a fresh list of nodes here: https://chainz.cryptoid.info/strat/#!network
Wallet instructions here: https://stratisplatform.com/download/Stratis_Wallet_Instructions.pdf

**Comment by steelliberty** [comment]
Yay .. Its running .. for those using a Mac %APPDATA% is:   ~/Library/Application Support/Stratis .
