### ISSUE TITLE
stratis-qt startup

### ISSUE THREAD

**Issue by anklesprain** [stratisproject/stratisX#22]
Starting the stratis-qt app on osx yosemite 10.10.5 gives this error:
[Process.docx](https://github.com/stratisproject/stratisX/files/1049963/Process.docx)

**Comment by dev0tion** [comment]
Hey @anklesprain,

Please use v2.0.0.1 instead: https://github.com/stratisproject/stratisX/releases/tag/v2.0.0.1

**Comment by anklesprain** [comment]
Hi,

I installed stratis-qt v 2.0.0.1 on my macbook (yosemite 10.10.5, after install I chose receive, copied the address and sent strat from poloniex. This was more than 10 hours ago. I attached a snapshot of how my wallet dashboard looks like. Also this is the tx id of the transaction: 44982ed17c567c11da905860aae316e16336d538f9f506a43cf05944cafdf140

Please help. Thanks. 
![screen shot 2017-06-04 at 21 47 04](https://cloud.githubusercontent.com/assets/29168168/26764476/3354187c-4970-11e7-939d-5a8c902f6d00.png)

**Comment by dev0tion** [comment]
Hey @anklesprain,

Please close your wallet and follow these steps:
- Use Finder to navigate to: ~/Library/Application Support/Stratis
- In that folder **DO NOT** remove your wallet.dat file, this cointains your funds
- Please remove all other files in that folder
- Start your wallet and let it sync again

Should be showing up after it's synced!

**Comment by anklesprain** [comment]
Hi

There is no Stratis folder in Application Support, nor anywhere on my computer. What now?

I can right click and show package contents on my stratis-qt icon, and I get to a folder structure which looks like the image attached. There is no wallet.dat file in any of the folders ... What can I do?
![screen shot 2017-06-06 at 23 55 29](https://user-images.githubusercontent.com/29168168/26851518-bda64aaa-4b13-11e7-983d-f2cb7019eea7.png)

**Comment by dev0tion** [comment]
There is a folder, but u need to navigate to it through the Finder menu:
Go -> Go to Folder (or something similar on ur OS language).

**Comment by anklesprain** [comment]
This is the contents of my app support folder, there is no stratis folder


![screen shot 2017-06-07 at 00 07 26](https://user-images.githubusercontent.com/29168168/26852022-6ab21ab6-4b15-11e7-84a5-398a5cefa6d2.png)

**Comment by dev0tion** [comment]
That is not the correct Application Support folder.
As I said, use Go -> Go to Folder -> enter ~/Library/Application Support/Stratis.

**Comment by anklesprain** [comment]
Nope :)

![screen shot 2017-06-07 at 00 15 22](https://user-images.githubusercontent.com/29168168/26852320-9bddf85c-4b16-11e7-8cb4-bb043e692fb6.png)
![screen shot 2017-06-07 at 00 15 07](https://user-images.githubusercontent.com/29168168/26852321-9be44af4-4b16-11e7-9b9d-b95d936227a4.png)
![screen shot 2017-06-07 at 00 15 37](https://user-images.githubusercontent.com/29168168/26852322-9bfbd160-4b16-11e7-80ed-ffec110fa7a1.png)

**Comment by anklesprain** [comment]
If I do this, I get this
![screen shot 2017-06-07 at 00 16 01](https://user-images.githubusercontent.com/29168168/26852356-b0d1ec78-4b16-11e7-9221-76037452e7ff.png)
![screen shot 2017-06-07 at 00 16 08](https://user-images.githubusercontent.com/29168168/26852357-b0ea1438-4b16-11e7-9a81-3f6fdd6dec49.png)

**Comment by dev0tion** [comment]
Haha, in none of the screenshots above the path was correct :D Everything in the line is important:
~/Library/Application Support/Stratis
Don't forget the ~ in the beginning and don't add a . at the end.

**Comment by anklesprain** [comment]
Shit, you are right, so now I close the wallet, delete everything in this folder except the wallet.dat file and restart my wallet and wait?
![screen shot 2017-06-07 at 00 23 27](https://user-images.githubusercontent.com/29168168/26852672-ae3fb80e-4b17-11e7-9530-d3d8463ca5e8.png)

**Comment by dev0tion** [comment]
Exactly @anklesprain

**Comment by anklesprain** [comment]
did all that, 5 minutes ago
![screen shot 2017-06-07 at 00 26 10](https://user-images.githubusercontent.com/29168168/26852742-f29d58b2-4b17-11e7-8138-6f9a711d59de.png)

**Comment by anklesprain** [comment]
@dev0tion still not synced, what about this reddit post? 
![screen shot 2017-06-07 at 00 44 05](https://user-images.githubusercontent.com/29168168/26853414-84bfedca-4b1a-11e7-8172-e29833c8213c.png)

**Comment by dev0tion** [comment]
@anklesprain yes, the only problem with your wallet now is that it has no connection.
The solution proposed on Reddit will work!
