### ISSUE TITLE
sent myself 20 coins

### ISSUE THREAD

**Issue by adfsads** [stratisproject/stratisX#24]
blockchain on cryptoid is showing I sent 140. 20 to myself and 120 to unknown address. Did I just lose 120 coins? How?

**Comment by dev0tion** [comment]
No. 120 was send back to yourself, that's called a change address.
You have a list of unspent transaction outputs (UTXO's), you can't spend half of an UTXO. It has to be spend completely, so the change is send back to you.

Nothing to worry about.
