### ISSUE TITLE
strat not transfered for more that 24h

### ISSUE THREAD

**Issue by anklesprain** [stratisproject/stratisX#25]
Hi,

I installed stratis-qt v 2.0.0.1 on my macbook (yosemite 10.10.5, after install I chose receive, copied the address and sent strat from poloniex. This was more than 10 hours ago. I attached a snapshot of how my wallet dashboard looks like. Also this is the tx id of the transaction: 44982ed17c567c11da905860aae316e16336d538f9f506a43cf05944cafdf140

Please help. Thanks.
![screen shot 2017-06-04 at 21 47 04](https://cloud.githubusercontent.com/assets/29168168/26779458/196858fa-49ee-11e7-9e3f-af018884f2e8.png)

**Comment by nickothman** [comment]
I have the same issue... have contacted support but haven't received any reply so far..

**Comment by dev0tion** [comment]
@anklesprain looks like u need to add some nodes, your wallet is out of sync.
If adding nodes doesn't help please check my solution here: 
https://github.com/stratisproject/stratisX/issues/23
