### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by Gulogomi** [stratisproject/stratisX#26]
Greetings everyone

I accidentally deleted the file that I wrote my password in on my computer. I'm not able to recover it using the built in Windows restore tool and I have tried several recovering softwares. I'm able to find the shortcut to the file under the "Recent" folder, but I'm not able to use it because the file itself is deleted.

Is it somehow possible to recover the password or "crack" the wallet?

**Comment by dev0tion** [comment]
You can try to bruteforce it, but it will not be easy.
