### ISSUE TITLE
stratis-qt wallet

### ISSUE THREAD

**Issue by anklesprain** [stratisproject/stratisX#28]
Did everything in issue 22: https://github.com/stratisproject/stratisX/issues/22
Did not work so why is the issue closed? 

I need a solution, please help me. I transferred strat from poloniex to my strat-qt wallet and it does not sync. It is becoming frustrating, what can I do?

**Comment by dev0tion** [comment]
@anklesprain I suggest you wait untill we have released the new version of the client, should be in the next few days.
You can try the things being explained in #23 as well, but if you're not too tech minded it's better to wait.

**Comment by anklesprain** [comment]
Ok I'll wait, but I'll be back if things are not sorted out

**Comment by nickothman** [comment]
@dev0tion - would my receive key be the same when the new release is out?
Thanks
Regards
Nick

**Comment by dev0tion** [comment]
Yes mate, as long as you do not remove the wallet.dat file it will remain the same.
If the new release doesn't work for you please join our slack: slackinvite.stratisplatform.com and ping me in the #support channel. I'll help you there! Easier than here.

**Comment by nickothman** [comment]
@dev0tion - Since I created the file with extras nodes the sync is faster
If I wanted to download the software again taking into account I have my backup and the wallet.dat file - How can I do that with loosing my key? Sorry for my ignorance...
Thanks
Regards
Nick

**Comment by nickothman** [comment]
meant without losing my key...

**Comment by dev0tion** [comment]
Solved through Slack.
