### ISSUE TITLE
Wallet not receiving funds.

### ISSUE THREAD

**Issue by Sinisterzad** [stratisproject/stratisX#30]
Yesterday I tried to transfer around 20 Stratis to my wallet, but it remains out of sync. I tried adding a stratis.conf file with the nodes, but it still hasn't synced. I used to changelly.com to transfer the funds and it says it worked, but I'm still not receiving the coins. http://imgur.com/j1OrJtP here's an image of the transaction

**Comment by dev0tion** [comment]
Hi @Sinisterzad 

Please follow the steps described here to get back in sync:
https://github.com/stratisproject/stratisX/releases/tag/v2.0.0.3

Please let me know if that fixed it for you!

Grts

**Comment by Sinisterzad** [comment]
Thank you, I finally fixed the issue by un-checking the 2 boxes in the network options page which started synchronization and I just received the funds!
