### ISSUE TITLE
Keeps crashing on start.  OSX Version:10.11.6, Wallet Version : 2.0.0.3

### ISSUE THREAD

**Issue by tmli3b3rm4n** [stratisproject/stratisX#32]
Keeps crashing on start.  OSX Version:10.11.6
**Wallet version 2.0.0.3**

``` Process:               Stratis-Qt [10302]
Path:                  /Applications/Stratis-Qt.app/Contents/MacOS/Stratis-Qt
Identifier:            co.stratis.Stratis-Qt
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Stratis-Qt [10302]
User ID:               1338005810

Date/Time:             2017-07-29 14:20:36.200 -0400
OS Version:            Mac OS X 10.11.6 (15G1510)
Report Version:        11
Anonymous UUID:        BD92D51D-4CFF-CBA6-3C32-94DD2BA42F6F

Sleep/Wake UUID:       49527246-4C30-45E8-954F-8163194D98C1

Time Awake Since Boot: 53000 seconds
Time Since Wake:       250 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY 

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010da61af8  rbx: 0x00007f952de89ca0  rcx: 0x0000000000000000  rdx: 0x000000000000000d
  rdi: 0x00007fff53c6e4d8  rsi: 0x0000000000000001  rbp: 0x00007fff53c6d4d0  rsp: 0x00007fff53c6d4b8
   r8: 0x00007f952d88f0f0   r9: 0x0000000000000000  r10: 0x000000010d05f701  r11: 0x000000010cb5f4b0
  r12: 0x00007f952de908d0  r13: 0x00007fff8674a4c0  r14: 0x00007f952d884c70  r15: 0x00007f952db3ea30
  rip: 0x000000010da61af8  rfl: 0x0000000000010202  cr2: 0x0000000114edf000
  
Logical CPU:     4
Error Code:      0x00000000
Trap Number:     6


```

**Comment by tmli3b3rm4n** [comment]
My bad changing title so many times.  Fat fingers and mimosas morning.  This is a valid issue though I confirmed 3 times, thinking the first time may have just been a different issue.

**Comment by aaronbesson** [comment]
same here, crashing on OSX while trying to load wallet (first time installer)

**Comment by sebge-1** [comment]
Same issue...please fix this Stratis.

**Comment by davidkillingsworth** [comment]
Same issue here:  Mac OS X 10.11.6

**Comment by kostar8** [comment]
Same here, Mac OS 10.11.6

**Comment by dev0tion** [comment]
Hi guys, thanks for raising this issue.
We have been aware of it for quite some time. It is not related to the OS X version, it's a very generic error which is hard to debug. Presumably it has something to do with the way Berkeley-DB has been compiled.

I guess you are all trying to run v2.0.0.3?
Please try running v2.0.0.2 for now: https://github.com/stratisproject/stratisX/releases/tag/v2.0.0.2

Let me know if that helped.

**Comment by Leon-CC** [comment]
i have tried both v2.0.0.2 as well as v2.0.0.3. i could not get any of them to work i am running a macbook late 2008 with OS 10.11.6 OS X El Capitan it. Does VM have anything to do with it because i know i cant run the Docker app on my macbook because it cant do the VMs

**Comment by kostar8** [comment]
This one worked for me for the MAC version.. still syncing though.. will keep Y'all updated.. Thx

**Comment by dev0tion** [comment]
@Leon-CC no, not being able to run VM's doesn't have anything to do with it.
Have you tried running v2.0.0.1?

@kostar8 good. All synced up now I guess?

**Comment by kostar8** [comment]
Why use VM when it works with MAC? Mine works on my Mac

**Comment by kostar8** [comment]
Yes, this works fine on my Mac.. I have it staking too..

**Comment by kostar8** [comment]
Thanks so much!

**Comment by terryrabinowitz** [comment]
I also have this problem with the new version but it looks like version 2.0.0.2 is ok.  It is syncing now...

**Comment by Clermont1** [comment]
v2002 is working. still not v2003. thanks

**Comment by Volk10** [comment]
Get every time the error to loading the blockchain. 
I had to do the folowing:

This should be fix fast guys. This is a big bug, scared me to dead. 


Please follow these steps carefully to fix the issue:
Close your wallet
Update to v2.0.0.3 of our wallet
For Windows: navigate to %appdata%/Stratis using the address bar in Windows Explorer
For OS X: navigate to ~/Library/Application Support/Stratis using Finder (Go menu -> Go to Folder)
In that folder DO NOT remove the wallet.dat file (you should have this file backed up anyway), as that contains all your funds
**Remove all the other files in the folder (again, NOT wallet.dat)**

Start your wallet and you should be good to go
