### ISSUE TITLE
Wallet: change directory where files are being downloaded when synchronizing

### ISSUE THREAD

**Issue by NoRabbit** [stratisproject/stratisX#37]
Right now the directory on windows is in appdata where my system is installed. This is a sdd and space is limited. I need to put the files on my other drive. Is it possible ?
thx.

**Comment by DemonRx** [comment]
When starting the wallet use `stratis-qt -datadir=/path/to/folder` 

i.e.

```bash
stratis-qt -datadir=D:\stratis\
```

**Comment by NoRabbit** [comment]
Thx a lot, sry if it was put somewhere but couldn't find it in the "official" docs (pdf) onhttps://stratisplatform.com/
