### ISSUE TITLE
Minimal amount of staking

### ISSUE THREAD

**Issue by munrocket** [stratisproject/stratisX#38]
Hello, can you tell me please minimal amount of staking now?
I need stratisX or breeze? I'm confused.

**Comment by dev0tion** [comment]
For staking you will need stratisX, there is no minimum requirement.
On average, 25 000 Stratis will get you 1 Stratis per day.

**Comment by munrocket** [comment]
@dev0tion thanks for reply.

So stratis is cryptocurrency with inflation model or this is early distribution? For what purpose do you have breeze project?

**Comment by dev0tion** [comment]
Stratis is the cryptocurrency for our mainchain, yes.
Breeze is a lightweight privacy wallet, focused on providing more private transactions for Bitcoin and later Stratis
