### ISSUE TITLE
bug in stratis wallet version v.2.0.0.3 mac os

### ISSUE THREAD

**Issue by ioakimis** [stratisproject/stratisX#39]
Hi Guys, I have the following issue with the stratis wallet : Today i wanted to transfer some coins on my wallet to an exchanger but I get the notification that my passphrase is wrong. However this is impossible, I have a file from July where the passphrase is saved and it is not modified since. I already unlocked my wallet at least four or five times before with this password. I also have a backup of my wallet and restored it but It didn’t help either. I read from other users that it might be a bug. Can you help me out with the matter i would be really greatful. I am almost at the point giving up as I said I have this file from July no sign that I modified it , I use it to copy / paste my password.
Thanks in advance for any help.

On Reddit : https://www.reddit.com/r/stratisplatform/comments/7fprxy/issue_with_stratis_wallet_can_not_access_the/

**Comment by ioakimis** [comment]
help

**Comment by dev0tion** [comment]
Hi, there is not much we can do about a wrong password, try uppercases/adding space before or after the password etc.

**Comment by ioakimis** [comment]
Hello, thanks for your reply.
As i told you in the text above the passphrase is definitely right as i saved my document in july and accessed and unlock the wallet in august and september successfully. I already tried uppercases/adding spaces and other variations.

**Comment by ioakimis** [comment]
Please help me out. I am confident the mistake is not coming from me.

**Comment by dev0tion** [comment]
When the password is wrong we are 100% sure it's user error @ioakimis, there is nothing we can do about it.

**Comment by ioakimis** [comment]
Thanks for your response dev0tion.
It may seem unrealistic that there is a bug, several users have experienced the same issue(several posts on reddit) It cant be a coincidence that everyone is so dumb that they forget the password. Since i successfully unlocked my wallet in september to make a transaction and the text file with the passphrase is not modified since July I cant see what i am doing wrong. It would be nice if i can send you the wallet.dat and the passphrase file you can take a look and may help me out if that is okay for you.

**Comment by ioakimis** [comment]
Hi buddy,

I also believe this is a bug because we saw multiple people reporting the same issue.

We tried to unlock it with your password, but it didn’t work.

Please keep us posted if you hear anything from the Strat Devs.

Regards,

John

**Comment by ioakimis** [comment]
this was a response from a walletrecovery service.

**Comment by ioakimis** [comment]
bump

**Comment by dev0tion** [comment]
@ioakimis there is nothing more to say, it is 100% up to the user to enter the correct password.
Each case in the past has been solved by the user remembering his/her correct password or trying various things that may have gone wrong when entering it in the first time (spaces, caps lock, keyboard layout change,...)

It is not a bug in the software, the Qt wallet software has been around for years and there are no password related bugs in it.

You can try to brute force it and use letters/digits that you are 100% sure of that they're in there.
