### ISSUE TITLE
Cant install the wallet

### ISSUE THREAD

**Issue by jasondean1337** [stratisproject/stratisX#41]
`bignum.h: In function 'bool operator>(const CBigNum&, const CBigNum&)':
bignum.h:720:83: error: cannot convert 'const CBigNum*' to 'const BIGNUM* {aka const bignum_st*}' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
 inline bool operator>(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) > 0); }
                                                                                   ^
makefile.unix:193: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1`

I always get that error when trying to install the wallet on my raspberry pi :/

**Comment by dev0tion** [comment]
Hi @jasondean1337,

Please find a solution here:
https://github.com/stratisproject/stratisX/issues/40

Closing the issue, feel free to reopen if that did not work for you.
