### ISSUE TITLE
g++: internal compiler error: Killed (program cc1plus) on raspi

### ISSUE THREAD

**Issue by EmGeI** [stratisproject/stratisX#42]
1st sorry for my bad english ;)

So, I had following error on build on my raspi3 : 
`g++: internal compiler error: Processus arrêté (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
makefile.unix:193 : la recette pour la cible « obj/init.o » a échouée
make: *** [obj/init.o] Erreur 4`

It's cause by out of memory
The workaround is add extra swap

> $free
sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
sudo mkswap /var/swap.img
sudo swapon /var/swap.img
free
make -f makefile.unix

**Comment by dev0tion** [comment]
Thank you @EmGeI
