### ISSUE TITLE
Initial sync is a no-go

### ISSUE THREAD

**Issue by Rav3nPL** [stratisproject/stratisX#43]
Because code is WAY outdated (from Bitcoin Core) there is no "header-first" synchronization.
Even when I run
```
stratis-qt.exe -maxorphanblocksmib=512 -timeout=200 -dbcache=512
```
I'm ending up witch around 25'000 "orphan blocks" in memory under block 125`000.
Default settings allow up to not connected 750 blocks in memory, and causes that node is downloading blocks more than once.

Also, there is some 
```
ERROR: AcceptToMemoryPool : nonstandard transaction: non-final
```
transaction/s send over network that is freezing daemon for 1-2 second every time it hits.
And when I have 16 connections it is sending to me ALOT.

Syncing process is very inefficient, my CPU is under 20% all time (not even one full core taken all time), almost no movement on SSD, network traffic <150MB in 30+ mins (90MB in /40MB out). on block <150`000.

My suggestion: move code base to at least Bitcoin Core 0.10
https://bitcoin.org/en/developer-guide#headers-first

**Comment by Rav3nPL** [comment]
Peak orphan blocks was over 38500
```
ProcessBlock: ORPHAN BLOCK 38562, prev=da5090d5c2974abee1aa6120acefc7853c6586fbc62f1fecaeddfbc7775877a0
ProcessBlock: ORPHAN BLOCK 38563, prev=6257da1ba5f5a213c65873f0baa94fa32ed0c08c24389c8421117ef9d95a29eb
ProcessBlock: ORPHAN BLOCK 38564, prev=b15ec782b1249460fd86a4a58cedf4b70a652b7ca6a85a9d96526181a43edf60
ProcessBlock: ORPHAN BLOCK 38565, prev=e14fc6a9d248abd88a5a76178ad8d8a5518aa8e6e795d31a0a4f6804b12be5a3
SetBestChain: new best=c602910c4e33d2a453a51ec5394981ffb59eb342f9a68a804713d682ba5e4bd3  height=465986  trust=4940801906564167299906  blocktrust=9561478619685652  date=08/01/17 14:47:12
ProcessBlock: ACCEPTED
SetBestChain: new best=1145bbeb8f51261d1808573c8b519023b55cb562f797fd00acb9f1ac1b9eb1b4  height=465987  trust=4940812105487084953871  blocktrust=10198922917653965  date=08/01/17 14:47:44
ProcessBlock: ACCEPTED
SetBestChain: new best=38ed6ac713773bb473af26059c9cdd390849a7c91c9a76648040d2fbbe3af502  height=465988  trust=4940822984360125940323  blocktrust=10878873040986452  date=08/01/17 14:49:52
ProcessBlock: ACCEPTED
SetBestChain: new best=ba1d5938a71a4b2b4094baf709a30ef11c3e9a3a00fd14a4a1370b05697f5813  height=465989  trust=4940832654484347024646  blocktrust=9670124221084323  date=08/01/17 14:52:16
ProcessBlock: ACCEPTED
```

**Comment by dev0tion** [comment]
Hi @Rav3nPL,

Please note that stratisX will be depricated after testing of our own full node has been completed:
https://github.com/stratisproject/StratisBitcoinFullNode
