### ISSUE TITLE
Crash on startup (St13runtime_error)

### ISSUE THREAD

**Issue by nicnick1** [stratisproject/stratisX#45]
Might be something on my end, but I'm at loss what it could be.
Error: -30974, can't open database stratis in Runaway exception.

**Comment by dev0tion** [comment]
Hey @nicnick1, sorry I must have missed this issue.
Are you still having issues starting the wallet?

**Comment by tommyranger** [comment]
Hello dev0tion,

I am having the same issue with version 2.0.0.3 and also with previous versions. Can you help please? I enclose a screenshot of the error message:

![image](https://user-images.githubusercontent.com/36209208/44732913-4280d080-aade-11e8-8071-eec99d9789bf.png)

Thanks
Tom

**Comment by DemonRx** [comment]
@tommyranger hello, be sure you don't have any instances of stratis running already, check in your task manager. This is the usual cause for that error. Whenever stratis is running it locks that directory so other wallets can't access it at the same time.

**Comment by tommyranger** [comment]
@D3m0nKingx thanks for the swift reply. I confirm that no other Stratis wallets (or any other wallets) are running. Checked in the Task Manager and made sure. Is there something else that would cause this?

**Comment by DemonRx** [comment]
Besides just restarting your system as the ultimate solution. Give one or two of these methods a try:

https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows

**Comment by tommyranger** [comment]
@D3m0nKingx Deleted everything (less the wallet.dat file) and started again. Downloaded the latest version and it synced with no issue. 

However a new issue has arisen...the wallet shuts itself down each time I attempt a 'send' transaction. When I reopen the wallet the transaction is non-existent and my balance remains the same.

**Comment by DemonRx** [comment]
@tommyranger we're on version 2.0.0.5, you need to upgrade.

**Comment by tommyranger** [comment]
Sorry to say I am on the latest version, 2.0.0.5

This is definitely a mystery. I input the correct information for the 'send' transaction. I make sure I have the correct amount (less the transaction fee). I make sure I have the correct address. I hit send, and confirm, and.......BANG, the wallet shuts down.

**Comment by DemonRx** [comment]
Go to the folder where the wallet.dat is located. and look in the debug.log file to see if there's any information there that might give clue as to what is going on.

**Comment by tommyranger** [comment]
I have the debug.log file up.

**Comment by tommyranger** [comment]
Perhaps I could email you a screenshot of the file, and you could take a look at it in your spare time, when you have a moment? I'm not sure what I'm looking at here to be honest.

**Comment by DemonRx** [comment]
Just upload it here in github when you're writing your reply you can attach the file by drag and drop or click on "selecting them" and choose it to add here.

**Comment by tommyranger** [comment]
Ah yes I see. Here is the file:
[debug.log](https://github.com/stratisproject/stratisX/files/2339686/debug.log)

**Comment by DemonRx** [comment]
Please delete the debug.log file from your directory. start the wallet, try to do a transaction. If it shuts down again, send the new debug.log file please

**Comment by tommyranger** [comment]
YES!! It worked. Thank you so much.

For your reference and for other readers who might have the same issue....I did exactly as you said...I deleted the debug.log file, reopened the wallet, then processed the transaction, and it worked straight away.

I really appreciate your help.

**Comment by DemonRx** [comment]
Yw! :100:  please close the issue, re-open if needed later.

**Comment by tommyranger** [comment]
Would you like a copy of the new debug.log file for your interest to see if there is anything different?

Also I'm happy to close this issue for you...I just don't know how. Please advise.

**Comment by DemonRx** [comment]
Sure that would be fine. Just click the comment and close button next to the green comment button. :stuck_out_tongue:

**Comment by tommyranger** [comment]
[debug.log](https://github.com/stratisproject/stratisX/files/2339779/debug.log)

I see a green comment button but I do not see a 'comment and close' button. Maybe I do not have permission from Github to close issues...

**Comment by DemonRx** [comment]
Ah sorry, you weren't the one that opened this issue that's why, @nicnick1 would have to if his issue is resolved.
