### ISSUE TITLE
Stratis Staking Wallet v2.0.0.3 failing to compile in Ubuntu 18.04

### ISSUE THREAD

**Issue by guttermonk** [stratisproject/stratisX#49]
Followed the instructions in the download and downloaded all the dependencies, but can't figure out why this fails to compile. Any help is greatly appreciated.

Here's a screenshot of what I got after entering "make": https://i.imgur.com/b7Id1zR.png

**Comment by dev0tion** [comment]
Hey @guttermonk, I haven't looked at 18.04 support yet.
I'm pretty sure downgrading the lib-ssl library works: https://github.com/stratisproject/stratisX/issues/33

Let me know if that worked for you.

**Comment by dev0tion** [comment]
Closing as above should solve the issue (tested building on 18.04  successfully).
Feel free to reopen if it doesn't solve the problem for you.

**Comment by guttermonk** [comment]
Do you have instructions on how to do this?

**Comment by guttermonk** [comment]
Also, any chance you can update the wallet to work with 18.04? The current wallet version is over a year old and no longer works with the current LTS version of Ubuntu. Adding a downloadable .deb, like Arc has, or adding a PPA, like Qtum has, would also be very helpful.

**Comment by dev0tion** [comment]
There are step by step instructions in the issue I posted above provided by JKGHPO.
As we are closing in on making our C# full node the default wallet, no resources will go into optimizing the C++ one.

**Comment by guttermonk** [comment]
Most of those steps look straight forward, but those instructions are for Raspbian and not Ubuntu. What should I do at the part where it says to set your repository list to point to "jessie" instead of "stretch"?
