### ISSUE TITLE
Recovering with Seed Key

### ISSUE THREAD

**Issue by eviwey38** [stratisproject/stratisX#52]
There is little documentation how to install on a new PC after the OLD PC crashed.

The instructions say to restore wallet.dat file, and even that part is vague.  In addtion, when old pc crashed I backed up my seed..  not the wallet.dat file.

There is little or no information how to activate my own seed when I do a new install.

And the biggest problem is that when I do activate my seed key and remove the old one, the wallet does not sync to the new balance.

How do I get the wallet to sync to the blockchain after activating my new seed?

**Comment by DemonRx** [comment]
@eviwey38 When you say "seed" you mean private key ? As in you went in the console and did: `dumpprivkey <STRATADDRESS>` ?

If  so, then you just need to use that private key and open your console and type:
 `importprivkey <privatekey>  true`

**Comment by eviwey38** [comment]
When you say "console" I'm assuming you are referring to the DOS prompt.
I renamed stratis-iq.exe to s.exe, and opened it to make sure it worked.
then i typed:   s dumpprivatekey     I not know what <STRATADDRESS> is so i skipped it.
then i typed:   s importprivkey <MY PRIVATE KEY HERE>
My balance is still 0.


Before I did the above I attempted this before contacting you:

I installed Stratis wallet on a NEW windows10 PC for staking (for my Old PC crashed.  I then synced the wallet to the Stratis blockchain, then went to settings/encrypt wallet and entered my 12 word private seed key.  After saving and restarting the wallet, my balance was still 0.

So, unable to access my personal Wallet.dat file, I deleted the exisiting (active) wallet.dat file after I closed the wallet.   I then opened the wallet and it shows 0 balance and it appears my 12 word passphrase has been removed.  It shows wallet is not encrypted...cause it asking for a passphrase if I try... just like after the fresh install of the Stratis wallet.    If i put my 12 word key in again, I would be duplicating what I did the first time, so I not think that will work.

I know my 12 word key, but I currently not have access to my other data (wallet.dat file & public key) and would like to begin staking again.  

Seems like if I have my key, I should be able to easily access my money.  How do I enter my private 12 word key to access my money.

thanks in advance

@eviwey

**Comment by DemonRx** [comment]
Ah, I hate to be the bearer of bad news, but that is not how the password  (or "key" as you refer to it) works in the Stratis-qt wallet. The password is only to ***unlock*** your wallet.dat file once it's loaded into Stratis-qt

To actually have access to the funds in the wallet.dat, you must have the private keys to your public stratis address. This is done by having the original wallet.dat you created (which is where the private keys are contained (encrypted)), or having the actual private keys themselves that belong to the respective pubkey (public Stratis Address), by having done `dumpprivkey <STRATADDRESS>` within the Stratis-qt Debug Console.

However, you're saying you don't have your wallet.dat file. Only the password to it. Unfortunately, unless you can locate the original or backup of your wallet.dat, or you have the private keys, there is no recovery of the funds.

**Comment by eviwey38** [comment]
Well... we are talking about over $30,000.

That is a lot of money to not know what I was doing when I thought I knew I
had it backed up.

I was deceived cause the other wallets I have used in the past I was able
to restore without the file...leaving me to think the 12 word key was all
you needed to create the Hash to access your funds.

Lets see if Acronis backed it up before my hard drive crashed.

**Comment by DemonRx** [comment]
I do hope you can find something sir. I don't know how you came to be misinformed that the password is a "key" you can recover your funds with in Stratis-qt.  But, that only applies to wallets like electrum, and what is now the new Stratis C# wallet.

**Comment by dev0tion** [comment]
I hope you find that backup @eviwey38.

We have backup documentation on our website: https://stratisplat.wpengine.com/wp-content/uploads/2016/08/Stratis_Wallet-Manual_v3.pdf 
Please read through it carefully when you set up a wallet next time, definitely when there's a lot of money involved.

**Comment by eviwey38** [comment]
D3m0nKingx,

Thank you for your support.

Acronis was updating their servers and they not allow me to access my
backups for a week or 2, but I finally did and was able to restore my
wallet of 3675 Stratis Coins.

*When I installed Stratis Wallet, I saw nothing about backing up the
wallet.dat file.  I read don't delete it...with no explanation why.... but
i did not read that i need back it up.*

*Also, how can I view my private keys?   If I back up my own incripted
private key, then I know I can always access my coins.  Right?*

*Mike*

**Comment by eviwey38** [comment]
what I meant is, I can backup my own keys...and encrypt them myself.  then
I know what is going on.

**Comment by DemonRx** [comment]
Great ! glad you got your coins ! 

My advice is go to the wallet console and type `dumpwallet walletdump.txt` this will create a file in the same location that stratis-qt is. and you can back that up, and if ever needed to restore your wallet just open a new wallet and do `importwallet /path/to/walletdump.txt`

**Comment by eviwey38** [comment]
How do I access the wallet "console"

**Comment by eviwey38** [comment]
1.   Where can I read about where to access the wallet console.

2.   If I unlock my wallet for staking, and someone else accesses my PC,
can they steel my funds?  I have a lot of Stratis I not want risk being
stolen.

Thank you in advance,

Michael P.
