### ISSUE TITLE
Still no Linux version?

### ISSUE THREAD

**Issue by openmindead** [stratisproject/stratisX#54]

**Comment by guttermonk** [comment]
They've abandoned development of the staking wallet to focus on the full node, and their instructions to install on 18.04 forces you to use old files (libssl-dev and it's dependencies) and to uninstall base OS programs like Snap, KDE Konnect, etc. 

See comments from their lead dev: #49

**Comment by guttermonk** [comment]
Finally figured out how to get the wallet running... Under Debian and Ubuntu it is possible to install an older libssl-dev lib, which doesn't uninstall other system files (unlike the method mentioned in #33 ):

sudo apt-get install libssl1.0-dev

This worked for me. Hope it helps!
