### ISSUE TITLE
I can not run Staking Wallet

### ISSUE THREAD

**Issue by Maxim3474** [stratisproject/stratisX#63]
Hi dear Developers, i have a problen with Staking Wallet, i downloaded it and if i run it, there is always a
diagnostic message from winrar: can not be performed "C:\Users\2BA0~1\AppData\Local\Temp\Rar$EXa11100.11574\stratis-qt.exe"

Thanks a lot

**Comment by DemonRx** [comment]
Are you trying to run stratis-qt.exe directly from the zip archive without extracting it first ?

**Comment by Maxim3474** [comment]
Staking Wallet was esrlier on my computer, i had some problems with Windows 10, i made reinstall with bug fixes but with file saving, then i downloaded a new one Stratis-Qt-v2.0.0.5-win and trying to open it with WinRar, it doesn't work.  Early it works on old Windows 10, i downloaded whole Blockchain and i have   Stratis.dat and my password for Stratis Staking Wallet. 
But now it doesen't starting to run with WinRar
![stratis wallet](https://user-images.githubusercontent.com/40694667/45171057-1a921b00-b20a-11e8-9fa9-5a8488b8aac7.png)

**Comment by DemonRx** [comment]
EXTRACT the file with WinRar, then open it (click on stratis-qt.exe) from the location you extracted it to (not from inside the zip file).

**Comment by Maxim3474** [comment]
I did it =) thanks a lot. It is now synchronizing, i have to wait =)
Now i have a Question, How can i restore my Wallet, i have:  1) Stratis.dat  2) my password for Wallet access, i tried to export (Stratis.dat) but this function doesn't work. Perhaps i have to do anything else?

**Comment by DemonRx** [comment]
Rename your "Stratis.dat" to **wallet.dat** and place into the C:\Users\2BA0~1\AppData\Roaming\Stratis  folder, then start the wallet and you should be all set :)

Once everything is ok, you can close this issue. you're welcome, and thank you :100:

**Comment by Maxim3474** [comment]
Thanks a Lot ;) it is made!
You are my GOD =))))))))

**Comment by Maxim3474** [comment]
Thanks a Lot ;) it is made!
You are my GOD =))))))))
