### ISSUE TITLE
Sends slow to confirm and getinfo reports obsolete?

### ISSUE THREAD

**Issue by Crypto2** [stratisproject/stratisX#67]
We are having a lot of issues lately with sends taking hours to confirm and getinfo is saying "Warning: This version is obsolete, upgrade required!" even though there isn't a new release?

**Comment by dev0tion** [comment]
Slow sending might be related to having a lot of UTXO's in one wallet. If that's the case it's a good idea to consolidate them.
The "version is obsolete" message occurs because our new C# node has higher block versions, but it's fine to keep using StratisX for now. 

Keep an eye out for any announcements, because at some point StratisX will be deprecated.

**Comment by Crypto2** [comment]
We only have maybe 200 unspents but will try consolidating them. Not sure how they would affect the time until the TX confirms though from when it is broadcast?

**Comment by dev0tion** [comment]
Ah sorry I misread - I thought they were taking long to send. In that case UTXOs won't have anything to do with it.
How many connections does the daemon have?

**Comment by Crypto2** [comment]
It has 8 connections.

**Comment by dev0tion** [comment]
Approximately how long does it take to confirm?

**Comment by Crypto2** [comment]
Most of the time confirms are within minutes, it's just rarely/randomly one will take like 4-8 hours to confirm. If it was BTC I would say fee spikes but not sure if you get those in the Stratis network.

**Comment by dev0tion** [comment]
Ok, within minutes is how it should always be.
When the transaction takes 4-8 hours to confirm, was the client on the tip of the chain?

**Comment by Crypto2** [comment]
As far as I know yes, unfortunately we usually don't know until a while later when someone asks about their withdrawal but I'll see if we can monitor that a bit.
